name: food_fellas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  chat_gpt_sdk: ^2.2.5
  dash_chat_2: ^0.0.20
  easy_stepper: ^0.8.3
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.0
  path_provider: ^2.0.5
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - .env

