name: food_fellas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  chat_gpt_sdk: ^2.2.5
  dash_chat_2: ^0.0.20
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/spaghettiBolognese.webp
    - .env

