name: food_fellas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  chat_gpt_sdk: ^3.1.0
  dash_chat_2: ^0.0.21
  flutter_gemini: ^2.0.5
  easy_stepper: ^0.8.3
  flutter_chat_ui: ^1.6.12
  flutter_dotenv: ^5.1.0
  typed_data: ^1.3.0
  image_picker: ^1.1.0
  path_provider: ^2.0.5
  path: ^1.8.0
  win32: ^5.5.4
  archive: ^3.6.1

  firebase_vertexai: ^0.2.2+4
  firebase_core: ^3.3.0
  flutter_markdown: ^0.7.3+1
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - .env