name: food_fellas
description: "A new Flutter project."
publish_to: "none"
version: 1.1.3+8

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  chat_gpt_sdk: ^3.1.0
  dash_chat_2: ^0.0.21
  flutter_gemini: ^3.0.0
  easy_stepper: ^0.8.3
  flutter_chat_ui: ^1.6.12
  flutter_dotenv: ^5.1.0
  typed_data: ^1.3.0
  image_picker: ^1.1.0
  path_provider: ^2.0.5
  path: ^1.8.0
  win32: ^5.5.4
  archive: ^3.6.1
  firebase_vertexai: ^1.0.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.1
  flutter_markdown: ^0.7.3+1
  cloud_firestore: ^5.2.1
  provider: ^6.1.2
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.2
  # For animations and illustrations
  flare_flutter: ^3.0.0
  lottie: ^3.2.0
  flutter_signin_button: ^2.0.0
  screenshot: ^3.0.0
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  open_peeps:
    path: ../open-peeps-main/packages/open_peeps
  #image_gallery_saver: ^2.0.3
  flutter_rating_bar: ^4.0.1
  emoji_picker_flutter: ^3.0.0
  http: ^1.2.2
  cloud_functions: ^5.1.3
  google_fonts: ^6.2.1
  flutter_expandable_fab: ^2.3.0
  speech_to_text: ^7.0.0
  image_cropper: ^8.0.2
  photo_view: ^0.15.0
  marquee: ^2.3.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  shared_preferences: ^2.3.4
  app_links: ^6.3.3
  share_plus: ^10.1.4
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  image: ^4.3.0
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4
  firebase_analytics: ^11.4.1
  font_awesome_flutter: ^9.2.0
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_image_compress: ^2.4.0
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  image_gallery_saver:
    git:
      url: https://github.com/eliasantony/image_gallery_saver
      ref: master

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/lottie/
    - lib/assets/brand/
    - lib/assets/tutorialGifs/
    - .env
